// flow-typed signature: 30a553961f8212388ba5e4c89bf9f582
// flow-typed version: <<STUB>>/evtjs_v^5.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'evtjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'evtjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'evtjs/lib/abi-cache' {
  declare module.exports: any;
}

declare module 'evtjs/lib/action' {
  declare module.exports: any;
}

declare module 'evtjs/lib/action.test' {
  declare module.exports: any;
}

declare module 'evtjs/lib/apiCaller' {
  declare module.exports: any;
}

declare module 'evtjs/lib/asset-cache' {
  declare module.exports: any;
}

declare module 'evtjs/lib/bigi/lib/bigi' {
  declare module.exports: any;
}

declare module 'evtjs/lib/bigi/lib/convert' {
  declare module.exports: any;
}

declare module 'evtjs/lib/bigi/lib/index' {
  declare module.exports: any;
}

declare module 'evtjs/lib/devtest' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/aes' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/api_common' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/api_object' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/common.test' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/ecdsa' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/ecsignature' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/enforce_types' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/hash' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/index' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/key_private' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/key_public' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/key_utils' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/object.test' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/promise-async' {
  declare module.exports: any;
}

declare module 'evtjs/lib/ecc/signature' {
  declare module.exports: any;
}

declare module 'evtjs/lib/evtConfig' {
  declare module.exports: any;
}

declare module 'evtjs/lib/evtLink' {
  declare module.exports: any;
}

declare module 'evtjs/lib/fetch' {
  declare module.exports: any;
}

declare module 'evtjs/lib/format' {
  declare module.exports: any;
}

declare module 'evtjs/lib/format.test' {
  declare module.exports: any;
}

declare module 'evtjs/lib/helper' {
  declare module.exports: any;
}

declare module 'evtjs/lib/index-old' {
  declare module.exports: any;
}

declare module 'evtjs/lib/index' {
  declare module.exports: any;
}

declare module 'evtjs/lib/index.test' {
  declare module.exports: any;
}

declare module 'evtjs/lib/key' {
  declare module.exports: any;
}

declare module 'evtjs/lib/logger' {
  declare module.exports: any;
}

declare module 'evtjs/lib/schema.test' {
  declare module.exports: any;
}

declare module 'evtjs/lib/schema/index' {
  declare module.exports: any;
}

declare module 'evtjs/lib/structs' {
  declare module.exports: any;
}

declare module 'evtjs/lib/structs.test' {
  declare module.exports: any;
}

declare module 'evtjs/lib/tmp' {
  declare module.exports: any;
}

declare module 'evtjs/pages/bip39' {
  declare module.exports: any;
}

// Filename aliases
declare module 'evtjs/lib/abi-cache.js' {
  declare module.exports: $Exports<'evtjs/lib/abi-cache'>;
}
declare module 'evtjs/lib/action.js' {
  declare module.exports: $Exports<'evtjs/lib/action'>;
}
declare module 'evtjs/lib/action.test.js' {
  declare module.exports: $Exports<'evtjs/lib/action.test'>;
}
declare module 'evtjs/lib/apiCaller.js' {
  declare module.exports: $Exports<'evtjs/lib/apiCaller'>;
}
declare module 'evtjs/lib/asset-cache.js' {
  declare module.exports: $Exports<'evtjs/lib/asset-cache'>;
}
declare module 'evtjs/lib/bigi/lib/bigi.js' {
  declare module.exports: $Exports<'evtjs/lib/bigi/lib/bigi'>;
}
declare module 'evtjs/lib/bigi/lib/convert.js' {
  declare module.exports: $Exports<'evtjs/lib/bigi/lib/convert'>;
}
declare module 'evtjs/lib/bigi/lib/index.js' {
  declare module.exports: $Exports<'evtjs/lib/bigi/lib/index'>;
}
declare module 'evtjs/lib/devtest.js' {
  declare module.exports: $Exports<'evtjs/lib/devtest'>;
}
declare module 'evtjs/lib/ecc/aes.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/aes'>;
}
declare module 'evtjs/lib/ecc/api_common.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/api_common'>;
}
declare module 'evtjs/lib/ecc/api_object.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/api_object'>;
}
declare module 'evtjs/lib/ecc/common.test.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/common.test'>;
}
declare module 'evtjs/lib/ecc/ecdsa.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/ecdsa'>;
}
declare module 'evtjs/lib/ecc/ecsignature.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/ecsignature'>;
}
declare module 'evtjs/lib/ecc/enforce_types.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/enforce_types'>;
}
declare module 'evtjs/lib/ecc/hash.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/hash'>;
}
declare module 'evtjs/lib/ecc/index.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/index'>;
}
declare module 'evtjs/lib/ecc/key_private.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/key_private'>;
}
declare module 'evtjs/lib/ecc/key_public.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/key_public'>;
}
declare module 'evtjs/lib/ecc/key_utils.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/key_utils'>;
}
declare module 'evtjs/lib/ecc/object.test.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/object.test'>;
}
declare module 'evtjs/lib/ecc/promise-async.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/promise-async'>;
}
declare module 'evtjs/lib/ecc/signature.js' {
  declare module.exports: $Exports<'evtjs/lib/ecc/signature'>;
}
declare module 'evtjs/lib/evtConfig.js' {
  declare module.exports: $Exports<'evtjs/lib/evtConfig'>;
}
declare module 'evtjs/lib/evtLink.js' {
  declare module.exports: $Exports<'evtjs/lib/evtLink'>;
}
declare module 'evtjs/lib/fetch.js' {
  declare module.exports: $Exports<'evtjs/lib/fetch'>;
}
declare module 'evtjs/lib/format.js' {
  declare module.exports: $Exports<'evtjs/lib/format'>;
}
declare module 'evtjs/lib/format.test.js' {
  declare module.exports: $Exports<'evtjs/lib/format.test'>;
}
declare module 'evtjs/lib/helper.js' {
  declare module.exports: $Exports<'evtjs/lib/helper'>;
}
declare module 'evtjs/lib/index-old.js' {
  declare module.exports: $Exports<'evtjs/lib/index-old'>;
}
declare module 'evtjs/lib/index.js' {
  declare module.exports: $Exports<'evtjs/lib/index'>;
}
declare module 'evtjs/lib/index.test.js' {
  declare module.exports: $Exports<'evtjs/lib/index.test'>;
}
declare module 'evtjs/lib/key.js' {
  declare module.exports: $Exports<'evtjs/lib/key'>;
}
declare module 'evtjs/lib/logger.js' {
  declare module.exports: $Exports<'evtjs/lib/logger'>;
}
declare module 'evtjs/lib/schema.test.js' {
  declare module.exports: $Exports<'evtjs/lib/schema.test'>;
}
declare module 'evtjs/lib/schema/index.js' {
  declare module.exports: $Exports<'evtjs/lib/schema/index'>;
}
declare module 'evtjs/lib/structs.js' {
  declare module.exports: $Exports<'evtjs/lib/structs'>;
}
declare module 'evtjs/lib/structs.test.js' {
  declare module.exports: $Exports<'evtjs/lib/structs.test'>;
}
declare module 'evtjs/lib/tmp.js' {
  declare module.exports: $Exports<'evtjs/lib/tmp'>;
}
declare module 'evtjs/pages/bip39.js' {
  declare module.exports: $Exports<'evtjs/pages/bip39'>;
}
