// flow-typed signature: c618549e3172d1ab948ae4e19f03aa37
// flow-typed version: <<STUB>>/node-fs-extra_v^0.8.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-fs-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-fs-extra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-fs-extra/lib/copy' {
  declare module.exports: any;
}

declare module 'node-fs-extra/lib/create' {
  declare module.exports: any;
}

declare module 'node-fs-extra/lib/index' {
  declare module.exports: any;
}

declare module 'node-fs-extra/lib/json' {
  declare module.exports: any;
}

declare module 'node-fs-extra/lib/mkdir' {
  declare module.exports: any;
}

declare module 'node-fs-extra/lib/output' {
  declare module.exports: any;
}

declare module 'node-fs-extra/lib/remove' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-fs-extra/lib/copy.js' {
  declare module.exports: $Exports<'node-fs-extra/lib/copy'>;
}
declare module 'node-fs-extra/lib/create.js' {
  declare module.exports: $Exports<'node-fs-extra/lib/create'>;
}
declare module 'node-fs-extra/lib/index.js' {
  declare module.exports: $Exports<'node-fs-extra/lib/index'>;
}
declare module 'node-fs-extra/lib/json.js' {
  declare module.exports: $Exports<'node-fs-extra/lib/json'>;
}
declare module 'node-fs-extra/lib/mkdir.js' {
  declare module.exports: $Exports<'node-fs-extra/lib/mkdir'>;
}
declare module 'node-fs-extra/lib/output.js' {
  declare module.exports: $Exports<'node-fs-extra/lib/output'>;
}
declare module 'node-fs-extra/lib/remove.js' {
  declare module.exports: $Exports<'node-fs-extra/lib/remove'>;
}
